- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: copy artifact into ec2 instance
  copy:
    src: artifact.tar.gz
    dest: ~/web

- name: extract zip artificat into ec2 instance
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web
    remote_src: yes

- name: Executing node
  shell: |
    cd ~/web
    ls ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start
  register: print_result  

- name: print job execution
  debug:
    msg: "{{ print_result.stdout_lines }}"  