- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: copy artifact into ec2 instance
  become: true
  copy:
    src: artifact.tar.gz
    dest: ~/web

- name: extract zip artificat into ec2 instance
  become: true
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web

- name: Executing node
  shell: |
    cd ~/web/artifact/backend
    npm install
    pm2 stop default
    # cd dist
    # pm2 start index.js
    pm2 start npm -- start