global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
    scheme: http
    timeout: 10s
    api_version: v1
rule_files:
- /etc/prometheus/rules.yml
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: udapeople
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  ec2_sd_configs:
  - endpoint: ""
    region: AWS_DEFAULT_REGION_HERE
    access_key: AWS_ACCESS_KEY_ID_HERE
    secret_key: AWS_SECRET_ACCESS_KEY_HERE
    refresh_interval: 1m
    port: 9100
    filters:
    - name: tag:project
      values:
      - udapeople