version: 2.1

defaults: &defaultsNode
  docker:
    - image: circleci/node:13.8.0

jobs:
  build-frontend:
    <<: *defaultsNode
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    <<: *defaultsNode
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
            # npm login
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    <<: *defaultsNode
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run: 
          name: Test front end  
          command: |
            cd frontend
            npm install
            npm run test        
  test-backend:
    <<: *defaultsNode
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: 
          name: Test back end  
          command: |
            cd backend
            npm install
            npm run test   
workflows:
  uda-people-workflow:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]